server:
  port: 8088

spring:
  profiles:
    active: dev
  application:
    name: blog-service
  datasource:
    url: jdbc:mysql://localhost:3306/blog-service?useSSL=false&serverTimezone=UTC  # 数据库 URL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      pool-name: HikariPool  # 连接池名称
      connection-timeout: 30000  # 连接池连接超时（毫秒）
      maximum-pool-size: 3  # 最大连接数
      minimum-idle: 2  # 最小空闲连接数
      idle-timeout: 30000  # 空闲连接超时时间（毫秒）
      max-lifetime: 600000  # 连接最大生命周期（毫秒）
  main:
    lazy-initialization: true  # 启用延迟初始化
  data:
    redis:
      host: localhost
      port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: ${JWT_SECRET}
  expiration-time: 43200000

digital-ocean:
  space-name: blog-content-service
  region: sgp1
  access-key: ${DIGITAL_OCEAN_ACCESS_KEY}
  secret-key: ${DIGITAL_OCEAN_SECRET_KEY}
  endpoint: https://sgp1.digitaloceanspaces.com
  cdn-endpoint: https://blog-content-service.sgp1.cdn.digitaloceanspaces.com/